import datetime
import decimal
import enum

import strawberry
from strawberry.tools import merge_types

from strawberry_resources.exporter import to_dict
from strawberry_resources.queries import Query as _Query
from strawberry_resources.types import FieldKind, FieldObjectKind


def test_to_dict():
    @strawberry.enum
    class SomeEnum(enum.Enum):
        FOO = "foo"
        BAR = strawberry.enum_value("bar", description="Bar")

    @strawberry.type
    class SomeType:
        id_field: strawberry.ID
        str_field: str
        int_field: int
        float_field: float
        decimal_field: decimal.Decimal
        date_field: datetime.date
        datetime_field: datetime.datetime
        time_field: datetime.time
        some_enum: SomeEnum

    @strawberry.type
    class Query:
        some_type: SomeType

    schema = strawberry.Schema(
        query=merge_types(
            "Query",
            (
                _Query,
                Query,
            ),
        ),
    )

    data = to_dict(schema)
    assert data == {
        "BaseFieldValidation": {
            "fields": [
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.BOOLEAN,
                    "label": "required",
                    "multiple": False,
                    "name": "required",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
            ],
            "name": "BaseFieldValidation",
        },
        "DecimalFieldValidation": {
            "fields": [
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.BOOLEAN,
                    "label": "required",
                    "multiple": False,
                    "name": "required",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.INT,
                    "label": "min_value",
                    "multiple": False,
                    "name": "minValue",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": False},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.INT,
                    "label": "max_value",
                    "multiple": False,
                    "name": "maxValue",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": False},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.INT,
                    "label": "max_digits",
                    "multiple": False,
                    "name": "maxDigits",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": False},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.INT,
                    "label": "decimal_places",
                    "multiple": False,
                    "name": "decimalPlaces",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": False},
                },
            ],
            "name": "DecimalFieldValidation",
        },
        "Field": {
            "fields": [
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.STRING,
                    "label": "name",
                    "multiple": False,
                    "name": "name",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": [
                        {"group": None, "label": "BOOLEAN", "value": "BOOLEAN"},
                        {"group": None, "label": "CURRENCY", "value": "CURRENCY"},
                        {"group": None, "label": "DATE", "value": "DATE"},
                        {"group": None, "label": "DATETIME", "value": "DATETIME"},
                        {"group": None, "label": "TIMEDELTA", "value": "TIMEDELTA"},
                        {"group": None, "label": "DECIMAL", "value": "DECIMAL"},
                        {"group": None, "label": "EMAIL", "value": "EMAIL"},
                        {"group": None, "label": "FILE", "value": "FILE"},
                        {"group": None, "label": "IMAGE", "value": "IMAGE"},
                        {"group": None, "label": "FLOAT", "value": "FLOAT"},
                        {"group": None, "label": "ID", "value": "ID"},
                        {"group": None, "label": "IP", "value": "IP"},
                        {"group": None, "label": "INT", "value": "INT"},
                        {"group": None, "label": "JSON", "value": "JSON"},
                        {"group": None, "label": "LEGAL_PERSON_DOC", "value": "LEGAL_PERSON_DOC"},
                        {
                            "group": None,
                            "label": "NATURAL_PERSON_DOC",
                            "value": "NATURAL_PERSON_DOC",
                        },
                        {"group": None, "label": "PASSWORD", "value": "PASSWORD"},
                        {"group": None, "label": "PERCENT", "value": "PERCENT"},
                        {"group": None, "label": "PHONE", "value": "PHONE"},
                        {"group": None, "label": "POSTAL_CODE", "value": "POSTAL_CODE"},
                        {"group": None, "label": "STRING", "value": "STRING"},
                        {"group": None, "label": "STRING_LIST", "value": "STRING_LIST"},
                        {"group": None, "label": "MULTILINE", "value": "MULTILINE"},
                        {"group": None, "label": "TIME", "value": "TIME"},
                        {"group": None, "label": "URL", "value": "URL"},
                        {"group": None, "label": "UUID", "value": "UUID"},
                        {"group": None, "label": "POINT", "value": "POINT"},
                        {"group": None, "label": "GEOPOINT", "value": "GEOPOINT"},
                        {"group": None, "label": "POLYGON", "value": "POLYGON"},
                        {"group": None, "label": "DISTANCE", "value": "DISTANCE"},
                    ],
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.STRING,
                    "label": "kind",
                    "multiple": False,
                    "name": "kind",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.STRING,
                    "label": "label",
                    "multiple": False,
                    "name": "label",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.BOOLEAN,
                    "label": "multiple",
                    "multiple": False,
                    "name": "multiple",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.BOOLEAN,
                    "label": "orderable",
                    "multiple": False,
                    "name": "orderable",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.BOOLEAN,
                    "label": "filterable",
                    "multiple": False,
                    "name": "filterable",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.STRING,
                    "label": "help_text",
                    "multiple": False,
                    "name": "helpText",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": False},
                },
                {
                    "fields": [
                        {
                            "choices": None,
                            "default_value": None,
                            "filterable": False,
                            "help_text": None,
                            "kind": FieldKind.STRING,
                            "label": "label",
                            "multiple": False,
                            "name": "label",
                            "orderable": False,
                            "resource": None,
                            "validation": {"required": True},
                        },
                        {
                            "choices": None,
                            "default_value": None,
                            "filterable": False,
                            "help_text": None,
                            "kind": FieldKind.STRING,
                            "label": "group",
                            "multiple": False,
                            "name": "group",
                            "orderable": False,
                            "resource": None,
                            "validation": {"required": False},
                        },
                    ],
                    "label": "choices",
                    "name": "choices",
                    "obj_kind": FieldObjectKind.OBJECT_LIST,
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.STRING,
                    "label": "resource",
                    "multiple": False,
                    "name": "resource",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": False},
                },
            ],
            "name": "Field",
        },
        "FieldChoice": {
            "fields": [
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.STRING,
                    "label": "label",
                    "multiple": False,
                    "name": "label",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.STRING,
                    "label": "group",
                    "multiple": False,
                    "name": "group",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": False},
                },
            ],
            "name": "FieldChoice",
        },
        "FieldObject": {
            "fields": [
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.STRING,
                    "label": "name",
                    "multiple": False,
                    "name": "name",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.STRING,
                    "label": "label",
                    "multiple": False,
                    "name": "label",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": [
                        {"group": None, "label": "OBJECT", "value": "OBJECT"},
                        {"group": None, "label": "OBJECT_LIST", "value": "OBJECT_LIST"},
                        {"group": None, "label": "INPUT", "value": "INPUT"},
                        {"group": None, "label": "INPUT_LIST", "value": "INPUT_LIST"},
                        {"group": None, "label": "LIST_INPUT", "value": "LIST_INPUT"},
                    ],
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.STRING,
                    "label": "obj_kind",
                    "multiple": False,
                    "name": "objKind",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
            ],
            "name": "FieldObject",
        },
        "IntFieldValidation": {
            "fields": [
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.BOOLEAN,
                    "label": "required",
                    "multiple": False,
                    "name": "required",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.INT,
                    "label": "min_value",
                    "multiple": False,
                    "name": "minValue",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": False},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.INT,
                    "label": "max_value",
                    "multiple": False,
                    "name": "maxValue",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": False},
                },
            ],
            "name": "IntFieldValidation",
        },
        "Query": {
            "fields": [
                {
                    "fields": [
                        {
                            "choices": None,
                            "default_value": None,
                            "filterable": False,
                            "help_text": None,
                            "kind": FieldKind.STRING,
                            "label": "name",
                            "multiple": False,
                            "name": "name",
                            "orderable": False,
                            "resource": None,
                            "validation": {"required": True},
                        },
                    ],
                    "label": "resources",
                    "name": "resources",
                    "obj_kind": FieldObjectKind.OBJECT_LIST,
                },
                {
                    "fields": [
                        {
                            "choices": None,
                            "default_value": None,
                            "filterable": False,
                            "help_text": None,
                            "kind": FieldKind.STRING,
                            "label": "name",
                            "multiple": False,
                            "name": "name",
                            "orderable": False,
                            "resource": None,
                            "validation": {"required": True},
                        },
                    ],
                    "label": "resource",
                    "name": "resource",
                    "obj_kind": FieldObjectKind.OBJECT,
                },
                {
                    "fields": [
                        {
                            "choices": None,
                            "default_value": None,
                            "filterable": False,
                            "help_text": None,
                            "kind": FieldKind.ID,
                            "label": "id_field",
                            "multiple": False,
                            "name": "idField",
                            "orderable": False,
                            "resource": None,
                            "validation": {"required": True},
                        },
                        {
                            "choices": None,
                            "default_value": None,
                            "filterable": False,
                            "help_text": None,
                            "kind": FieldKind.STRING,
                            "label": "str_field",
                            "multiple": False,
                            "name": "strField",
                            "orderable": False,
                            "resource": None,
                            "validation": {"required": True},
                        },
                        {
                            "choices": None,
                            "default_value": None,
                            "filterable": False,
                            "help_text": None,
                            "kind": FieldKind.INT,
                            "label": "int_field",
                            "multiple": False,
                            "name": "intField",
                            "orderable": False,
                            "resource": None,
                            "validation": {"required": True},
                        },
                        {
                            "choices": None,
                            "default_value": None,
                            "filterable": False,
                            "help_text": None,
                            "kind": FieldKind.FLOAT,
                            "label": "float_field",
                            "multiple": False,
                            "name": "floatField",
                            "orderable": False,
                            "resource": None,
                            "validation": {"required": True},
                        },
                        {
                            "choices": None,
                            "default_value": None,
                            "filterable": False,
                            "help_text": None,
                            "kind": FieldKind.DECIMAL,
                            "label": "decimal_field",
                            "multiple": False,
                            "name": "decimalField",
                            "orderable": False,
                            "resource": None,
                            "validation": {"required": True},
                        },
                        {
                            "choices": None,
                            "default_value": None,
                            "filterable": False,
                            "help_text": None,
                            "kind": FieldKind.DATE,
                            "label": "date_field",
                            "multiple": False,
                            "name": "dateField",
                            "orderable": False,
                            "resource": None,
                            "validation": {"required": True},
                        },
                        {
                            "choices": None,
                            "default_value": None,
                            "filterable": False,
                            "help_text": None,
                            "kind": FieldKind.DATETIME,
                            "label": "datetime_field",
                            "multiple": False,
                            "name": "datetimeField",
                            "orderable": False,
                            "resource": None,
                            "validation": {"required": True},
                        },
                        {
                            "choices": None,
                            "default_value": None,
                            "filterable": False,
                            "help_text": None,
                            "kind": FieldKind.TIME,
                            "label": "time_field",
                            "multiple": False,
                            "name": "timeField",
                            "orderable": False,
                            "resource": None,
                            "validation": {"required": True},
                        },
                        {
                            "choices": [
                                {"group": None, "label": "FOO", "value": "FOO"},
                                {"group": None, "label": "Bar", "value": "BAR"},
                            ],
                            "default_value": None,
                            "filterable": False,
                            "help_text": None,
                            "kind": FieldKind.STRING,
                            "label": "some_enum",
                            "multiple": False,
                            "name": "someEnum",
                            "orderable": False,
                            "resource": None,
                            "validation": {"required": True},
                        },
                    ],
                    "label": "some_type",
                    "name": "someType",
                    "obj_kind": FieldObjectKind.OBJECT,
                },
            ],
            "name": "Query",
        },
        "Resource": {
            "fields": [
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.STRING,
                    "label": "name",
                    "multiple": False,
                    "name": "name",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
            ],
            "name": "Resource",
        },
        "SomeType": {
            "fields": [
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.ID,
                    "label": "id_field",
                    "multiple": False,
                    "name": "idField",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.STRING,
                    "label": "str_field",
                    "multiple": False,
                    "name": "strField",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.INT,
                    "label": "int_field",
                    "multiple": False,
                    "name": "intField",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.FLOAT,
                    "label": "float_field",
                    "multiple": False,
                    "name": "floatField",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.DECIMAL,
                    "label": "decimal_field",
                    "multiple": False,
                    "name": "decimalField",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.DATE,
                    "label": "date_field",
                    "multiple": False,
                    "name": "dateField",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.DATETIME,
                    "label": "datetime_field",
                    "multiple": False,
                    "name": "datetimeField",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.TIME,
                    "label": "time_field",
                    "multiple": False,
                    "name": "timeField",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": [
                        {"group": None, "label": "FOO", "value": "FOO"},
                        {"group": None, "label": "Bar", "value": "BAR"},
                    ],
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.STRING,
                    "label": "some_enum",
                    "multiple": False,
                    "name": "someEnum",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
            ],
            "name": "SomeType",
        },
        "StringFieldValidation": {
            "fields": [
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.BOOLEAN,
                    "label": "required",
                    "multiple": False,
                    "name": "required",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": True},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.INT,
                    "label": "min_length",
                    "multiple": False,
                    "name": "minLength",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": False},
                },
                {
                    "choices": None,
                    "default_value": None,
                    "filterable": False,
                    "help_text": None,
                    "kind": FieldKind.INT,
                    "label": "max_length",
                    "multiple": False,
                    "name": "maxLength",
                    "orderable": False,
                    "resource": None,
                    "validation": {"required": False},
                },
            ],
            "name": "StringFieldValidation",
        },
    }


def test_to_dict_no_nulls():
    @strawberry.enum
    class SomeEnum(enum.Enum):
        FOO = "foo"
        BAR = strawberry.enum_value("bar", description="Bar")

    @strawberry.type
    class SomeType:
        id_field: strawberry.ID
        str_field: str
        int_field: int
        float_field: float
        decimal_field: decimal.Decimal
        date_field: datetime.date
        datetime_field: datetime.datetime
        time_field: datetime.time
        some_enum: SomeEnum

    @strawberry.type
    class Query:
        some_type: SomeType

    schema = strawberry.Schema(
        query=merge_types(
            "Query",
            (
                _Query,
                Query,
            ),
        ),
    )

    data = to_dict(schema, remove_nulls=True)
    __import__("pprint").pprint(data)
    assert data == {
        "BaseFieldValidation": {
            "fields": {
                "required": {
                    "kind": FieldKind.BOOLEAN,
                    "label": "required",
                    "name": "required",
                    "validation": {"required": True},
                },
            },
            "name": "BaseFieldValidation",
        },
        "DecimalFieldValidation": {
            "fields": {
                "decimalPlaces": {
                    "kind": FieldKind.INT,
                    "label": "decimal_places",
                    "name": "decimalPlaces",
                    "validation": {"required": False},
                },
                "maxDigits": {
                    "kind": FieldKind.INT,
                    "label": "max_digits",
                    "name": "maxDigits",
                    "validation": {"required": False},
                },
                "maxValue": {
                    "kind": FieldKind.INT,
                    "label": "max_value",
                    "name": "maxValue",
                    "validation": {"required": False},
                },
                "minValue": {
                    "kind": FieldKind.INT,
                    "label": "min_value",
                    "name": "minValue",
                    "validation": {"required": False},
                },
                "required": {
                    "kind": FieldKind.BOOLEAN,
                    "label": "required",
                    "name": "required",
                    "validation": {"required": True},
                },
            },
            "name": "DecimalFieldValidation",
        },
        "Field": {
            "fields": {
                "choices": {
                    "fields": {
                        "group": {
                            "kind": FieldKind.STRING,
                            "label": "group",
                            "name": "group",
                            "validation": {"required": False},
                        },
                        "label": {
                            "kind": FieldKind.STRING,
                            "label": "label",
                            "name": "label",
                            "validation": {"required": True},
                        },
                    },
                    "label": "choices",
                    "name": "choices",
                    "objKind": FieldObjectKind.OBJECT_LIST,
                },
                "filterable": {
                    "kind": FieldKind.BOOLEAN,
                    "label": "filterable",
                    "name": "filterable",
                    "validation": {"required": True},
                },
                "helpText": {
                    "kind": FieldKind.STRING,
                    "label": "help_text",
                    "name": "helpText",
                    "validation": {"required": False},
                },
                "kind": {
                    "choices": [
                        {"label": "BOOLEAN", "value": "BOOLEAN"},
                        {"label": "CURRENCY", "value": "CURRENCY"},
                        {"label": "DATE", "value": "DATE"},
                        {"label": "DATETIME", "value": "DATETIME"},
                        {"label": "TIMEDELTA", "value": "TIMEDELTA"},
                        {"label": "DECIMAL", "value": "DECIMAL"},
                        {"label": "EMAIL", "value": "EMAIL"},
                        {"label": "FILE", "value": "FILE"},
                        {"label": "IMAGE", "value": "IMAGE"},
                        {"label": "FLOAT", "value": "FLOAT"},
                        {"label": "ID", "value": "ID"},
                        {"label": "IP", "value": "IP"},
                        {"label": "INT", "value": "INT"},
                        {"label": "JSON", "value": "JSON"},
                        {"label": "LEGAL_PERSON_DOC", "value": "LEGAL_PERSON_DOC"},
                        {"label": "NATURAL_PERSON_DOC", "value": "NATURAL_PERSON_DOC"},
                        {"label": "PASSWORD", "value": "PASSWORD"},
                        {"label": "PERCENT", "value": "PERCENT"},
                        {"label": "PHONE", "value": "PHONE"},
                        {"label": "POSTAL_CODE", "value": "POSTAL_CODE"},
                        {"label": "STRING", "value": "STRING"},
                        {"label": "STRING_LIST", "value": "STRING_LIST"},
                        {"label": "MULTILINE", "value": "MULTILINE"},
                        {"label": "TIME", "value": "TIME"},
                        {"label": "URL", "value": "URL"},
                        {"label": "UUID", "value": "UUID"},
                        {"label": "POINT", "value": "POINT"},
                        {"label": "GEOPOINT", "value": "GEOPOINT"},
                        {"label": "POLYGON", "value": "POLYGON"},
                        {"label": "DISTANCE", "value": "DISTANCE"},
                    ],
                    "kind": FieldKind.STRING,
                    "label": "kind",
                    "name": "kind",
                    "validation": {"required": True},
                },
                "label": {
                    "kind": FieldKind.STRING,
                    "label": "label",
                    "name": "label",
                    "validation": {"required": True},
                },
                "multiple": {
                    "kind": FieldKind.BOOLEAN,
                    "label": "multiple",
                    "name": "multiple",
                    "validation": {"required": True},
                },
                "name": {
                    "kind": FieldKind.STRING,
                    "label": "name",
                    "name": "name",
                    "validation": {"required": True},
                },
                "orderable": {
                    "kind": FieldKind.BOOLEAN,
                    "label": "orderable",
                    "name": "orderable",
                    "validation": {"required": True},
                },
                "resource": {
                    "kind": FieldKind.STRING,
                    "label": "resource",
                    "name": "resource",
                    "validation": {"required": False},
                },
            },
            "name": "Field",
        },
        "FieldChoice": {
            "fields": {
                "group": {
                    "kind": FieldKind.STRING,
                    "label": "group",
                    "name": "group",
                    "validation": {"required": False},
                },
                "label": {
                    "kind": FieldKind.STRING,
                    "label": "label",
                    "name": "label",
                    "validation": {"required": True},
                },
            },
            "name": "FieldChoice",
        },
        "FieldObject": {
            "fields": {
                "label": {
                    "kind": FieldKind.STRING,
                    "label": "label",
                    "name": "label",
                    "validation": {"required": True},
                },
                "name": {
                    "kind": FieldKind.STRING,
                    "label": "name",
                    "name": "name",
                    "validation": {"required": True},
                },
                "objKind": {
                    "choices": [
                        {"label": "OBJECT", "value": "OBJECT"},
                        {"label": "OBJECT_LIST", "value": "OBJECT_LIST"},
                        {"label": "INPUT", "value": "INPUT"},
                        {"label": "INPUT_LIST", "value": "INPUT_LIST"},
                        {"label": "LIST_INPUT", "value": "LIST_INPUT"},
                    ],
                    "kind": FieldKind.STRING,
                    "label": "obj_kind",
                    "name": "objKind",
                    "validation": {"required": True},
                },
            },
            "name": "FieldObject",
        },
        "IntFieldValidation": {
            "fields": {
                "maxValue": {
                    "kind": FieldKind.INT,
                    "label": "max_value",
                    "name": "maxValue",
                    "validation": {"required": False},
                },
                "minValue": {
                    "kind": FieldKind.INT,
                    "label": "min_value",
                    "name": "minValue",
                    "validation": {"required": False},
                },
                "required": {
                    "kind": FieldKind.BOOLEAN,
                    "label": "required",
                    "name": "required",
                    "validation": {"required": True},
                },
            },
            "name": "IntFieldValidation",
        },
        "Query": {
            "fields": {
                "resource": {
                    "fields": {
                        "name": {
                            "kind": FieldKind.STRING,
                            "label": "name",
                            "name": "name",
                            "validation": {"required": True},
                        },
                    },
                    "label": "resource",
                    "name": "resource",
                    "objKind": FieldObjectKind.OBJECT,
                },
                "resources": {
                    "fields": {
                        "name": {
                            "kind": FieldKind.STRING,
                            "label": "name",
                            "name": "name",
                            "validation": {"required": True},
                        },
                    },
                    "label": "resources",
                    "name": "resources",
                    "objKind": FieldObjectKind.OBJECT_LIST,
                },
                "someType": {
                    "fields": {
                        "dateField": {
                            "kind": FieldKind.DATE,
                            "label": "date_field",
                            "name": "dateField",
                            "validation": {"required": True},
                        },
                        "datetimeField": {
                            "kind": FieldKind.DATETIME,
                            "label": "datetime_field",
                            "name": "datetimeField",
                            "validation": {"required": True},
                        },
                        "decimalField": {
                            "kind": FieldKind.DECIMAL,
                            "label": "decimal_field",
                            "name": "decimalField",
                            "validation": {"required": True},
                        },
                        "floatField": {
                            "kind": FieldKind.FLOAT,
                            "label": "float_field",
                            "name": "floatField",
                            "validation": {"required": True},
                        },
                        "idField": {
                            "kind": FieldKind.ID,
                            "label": "id_field",
                            "name": "idField",
                            "validation": {"required": True},
                        },
                        "intField": {
                            "kind": FieldKind.INT,
                            "label": "int_field",
                            "name": "intField",
                            "validation": {"required": True},
                        },
                        "someEnum": {
                            "choices": [
                                {"label": "FOO", "value": "FOO"},
                                {"label": "Bar", "value": "BAR"},
                            ],
                            "kind": FieldKind.STRING,
                            "label": "some_enum",
                            "name": "someEnum",
                            "validation": {"required": True},
                        },
                        "strField": {
                            "kind": FieldKind.STRING,
                            "label": "str_field",
                            "name": "strField",
                            "validation": {"required": True},
                        },
                        "timeField": {
                            "kind": FieldKind.TIME,
                            "label": "time_field",
                            "name": "timeField",
                            "validation": {"required": True},
                        },
                    },
                    "label": "some_type",
                    "name": "someType",
                    "objKind": FieldObjectKind.OBJECT,
                },
            },
            "name": "Query",
        },
        "Resource": {
            "fields": {
                "name": {
                    "kind": FieldKind.STRING,
                    "label": "name",
                    "name": "name",
                    "validation": {"required": True},
                },
            },
            "name": "Resource",
        },
        "SomeType": {
            "fields": {
                "dateField": {
                    "kind": FieldKind.DATE,
                    "label": "date_field",
                    "name": "dateField",
                    "validation": {"required": True},
                },
                "datetimeField": {
                    "kind": FieldKind.DATETIME,
                    "label": "datetime_field",
                    "name": "datetimeField",
                    "validation": {"required": True},
                },
                "decimalField": {
                    "kind": FieldKind.DECIMAL,
                    "label": "decimal_field",
                    "name": "decimalField",
                    "validation": {"required": True},
                },
                "floatField": {
                    "kind": FieldKind.FLOAT,
                    "label": "float_field",
                    "name": "floatField",
                    "validation": {"required": True},
                },
                "idField": {
                    "kind": FieldKind.ID,
                    "label": "id_field",
                    "name": "idField",
                    "validation": {"required": True},
                },
                "intField": {
                    "kind": FieldKind.INT,
                    "label": "int_field",
                    "name": "intField",
                    "validation": {"required": True},
                },
                "someEnum": {
                    "choices": [{"label": "FOO", "value": "FOO"}, {"label": "Bar", "value": "BAR"}],
                    "kind": FieldKind.STRING,
                    "label": "some_enum",
                    "name": "someEnum",
                    "validation": {"required": True},
                },
                "strField": {
                    "kind": FieldKind.STRING,
                    "label": "str_field",
                    "name": "strField",
                    "validation": {"required": True},
                },
                "timeField": {
                    "kind": FieldKind.TIME,
                    "label": "time_field",
                    "name": "timeField",
                    "validation": {"required": True},
                },
            },
            "name": "SomeType",
        },
        "StringFieldValidation": {
            "fields": {
                "maxLength": {
                    "kind": FieldKind.INT,
                    "label": "max_length",
                    "name": "maxLength",
                    "validation": {"required": False},
                },
                "minLength": {
                    "kind": FieldKind.INT,
                    "label": "min_length",
                    "name": "minLength",
                    "validation": {"required": False},
                },
                "required": {
                    "kind": FieldKind.BOOLEAN,
                    "label": "required",
                    "name": "required",
                    "validation": {"required": True},
                },
            },
            "name": "StringFieldValidation",
        },
    }
